name: Create Component
description: Fill out this form to create a new component
labels: ["create-component"]
body:
  - type: input
    id: desc
    attributes:
      label: Component Description
      description: Enter the description of the component you are trying to make
      placeholder: ex. an input box with large font and a search icon on the left hand side rounded corners
    validations:
      required: true
