name: Update Component
description: Fill out this form to create a new component
labels: ["update-component"]
body:
  - type: dropdown
  - NewComponent
    id: component
    attributes:
      label: Component Name
      description: Name of the component being updated
      options: 
      - Avatar
      - Button
      - ChatBubble
    validations:
      required: true
  - type: input
    id: desc
    attributes:
      label: Update Instructions
      description: Enter the description of the component you are trying to make
      placeholder: ex. an input box with large font and a search icon on the left hand side rounded corners
    validations:
      required: true
