name: Create Component
on:
  issues:
    types: [opened]

jobs:
  issue_handler:
    if: contains(github.event.issue.labels.*.name, 'create-component')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Component (GPT 3.5 Turbo)
        uses: ./.github/actions/create-component
        id: create_component
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          LLM_MODEL: "gpt-3.5-turbo"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_API_KEY }}
          labels: "create-component"
          title: "${{ github.event.issue.title }} - closes #${{ github.event.issue.number }}"
          commit-message: "${{ github.event.issue.title }} - closes #${{ github.event.issue.number }}"
          body: ${{ github.event.issue.body }}
          branch: "issue-${{ github.event.issue.number }}-update"
          add-paths: |
            src/components/atoms
