name: PR Comment Create
on:
  issue_comment:
    types: [created]

jobs:
  pr_comment_handler:
    if: github.event.issue.pull_request && (contains(github.event.comment.body, 'gpt3') || contains(github.event.comment.body, 'gpt-3'))
    runs-on: ubuntu-latest
    steps:
      - name: Set Env Vars
        id: setup
        run: |
          echo "${{ github.event.issue.title }}"
          TICKET_NUMBER=$(echo "${{ github.event.issue.title }}" | sed -n 's/.*#\([0-9]\+\).*/\1/p')
          echo "TICKET_NUMBER=$TICKET_NUMBER" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "issue-${{ steps.setup.outputs.TICKET_NUMBER }}-update"

      - name: Update Component based on comment (GPT 3.5 Turbo)
        uses: ./.github/actions/pull-request-comment
        id: component_code_gen
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          LLM_MODEL: "gpt-3.5-turbo"

      - name: Update file in git
        run: |
          npx prettier --write src/components/atoms
          git config user.email "brettlamy@gmail.com"
          git config user.name "Brett Lamy"
          git add src/components/atoms
          git commit -m "${{ steps.component_code_gen.outputs.componentName }} - closes #${{ github.event.issue.number }}"
          git push origin issue-${{ github.event.issue.number }}-update
