name: Issue Created Action
on:
  issues:
    types: [opened]

jobs:
  issue_handler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue author: ${{ github.event.issue.user.login }}"
      
      - name: Call API and update file
        id: api_call
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          RESPONSE=$(curl --request POST \
            --url https://api.example.com/endpoint \
            --header 'authorization: Bearer ${{ env.API_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "issue_title": "${{ github.event.issue.title }}",
              "issue_body": "${{ github.event.issue.body }}",
              "issue_author": "${{ github.event.issue.user.login }}"
            }' \
            --fail)
          echo "::set-output name=response::$RESPONSE"

      - name: Create and switch to new branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b issue-${{ github.event.issue.number }}-update

      - name: Update file with API response
        run: |
          echo "${{ steps.api_call.outputs.response }}" > updated_file.txt
          git add updated_file.txt
          git commit -m "Update file with API response"

      - name: Push changes to the new branch
        run: git push origin issue-${{ github.event.issue.number }}-update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update file with API response for issue #${{ github.event.issue.number }}"
          body: "This PR updates the file with the API response for issue #${{ github.event.issue.number }}."
          branch: issue-${{ github.event.issue.number }}-update
